<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Trasiego.Infraestructura</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trasiego.Aplicacion\Trasiego.Aplicacion.csproj" />
    <ProjectReference Include="..\Trasiego.Dominio\Trasiego.Dominio.csproj" />
  </ItemGroup>

</Project>
